apiVersion: cert-manager.io/v1 
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  
spec:
  IssuerConfig:
    acme:
      server: https://acme-v02.api.letsencrypt.org/directory
      email: idosegev.de@gmail.com
      privateKeySecretRef:
        name: letsencrypt-prod
      solvers:
      - selector: {}
        http01:
          ingress:
            class: nginx