apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.letsencrypt.org/directory
    email: 'idosegev.de@gmail.com'
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}